language: android
android:
  components:
  - tools
  - platform-tools
  - tools

  - build-tools-26.0.1
  - android-26

  - sys-img-armeabi-v7a-android-21

notifications:
  email:
    - ron.rcf@gmail.com