language: android
android:
  components:
  - tools
  - platform-tools
  - tools

  - build-tools-26.0.1
  - android-26

  - sys-img-armeabi-v7a-android-22

before_script:
  - echo no | android list targets
  - echo no | android create avd -f -n test -t "android-22" --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

notifications:
  email:
    - ron.rcf@gmail.com